### ISSUE TITLE
version names

### ISSUE THREAD

**Issue by colemy** [bl4ckscor3/BiomeInfo#3]
the 1.14.3 version of biome info v1.2.3 is named as 1.14.x on curse
however it is not compatible with 1.14.2 so it should be named as 1.14.3 not 1.14.x

**Comment by bl4ckscor3** [comment]
Disclaimer: This is not the place for issues regarding the CurseForge page, please use the comments on there for issues like these. This issue tracker is only for issues with the mod itself.

I included 1.14.x in the file because there will be a 1.14.4 and mods will most likely be compatible with it. The version tags on the 1.14.x file tell you that it's only compatible with 1.14.3. There's also a 1.14.2 file which you can use for Minecraft 1.14.2.
I will not do anything about this, as simply reading and using a bit of logic makes this problem non-existent.
