### ISSUE TITLE
Using other HUD mods may obscure biome info

### ISSUE THREAD

**Issue by EGOIST1372** [bl4ckscor3/BiomeInfo#8]
Hi
I love to have this mod beside my coordinates and fps and with many HUD mods it just overlap with the texts of other mods
example: incompatible with [ASH(another simple hud)](https://www.curseforge.com/minecraft/mc-mods/ash-another-simple-hud) mod
![image](https://user-images.githubusercontent.com/86555131/156237786-168cf63b-4d11-4934-9f59-280f1b246724.png)

it would be great if you could add a position option for it like an option to move it by 50 pixel right and a bit down 
thanks in advance <3

**Comment by bl4ckscor3** [comment]
Are you talking about the Fabric version of the mod? If you are not: The Forge version _does_ have plenty of configurability - including moving the text around.

Also I wouldn't call this incompatible, since the mod still works. It just isn't displayed well as a consequence of using multiple HUD mods.

**Comment by EGOIST1372** [comment]
yeah the fabric version
it would be great if we can get options that you say forge has ;-;
thanks

**Comment by bl4ckscor3** [comment]
Version 10 has been released to add the same config options that are present in the Forge edition https://www.curseforge.com/minecraft/mc-mods/biomeinfo-fabric/files/3670059

**Comment by EGOIST1372** [comment]
thanks so much <3
